#ifndef MACOS_DEBUG_FLAGS_H
#define MACOS_DEBUG_FLAGS_H

#define DEBUG_CAMERA_PATH_WIREFRAME_VISIBLE 0
#define DEBUG_CAMERA_FIXATION_POINT_VISIBLE 1
#define DEBUG_CAMERA_PROPERTIES_VISIBLE 0

#define DEBUG_FPS_COUNTER_ADVANCED_VISIBLE 0

#endif